fail_fast: true
default_stages: [commit]
repos:
- repo: local
  hooks:
    - id: format
      name: Format
      entry: make format
      language: system
      verbose: false
    - id: lint
      name: Lint
      entry: make lint
      language: system
      verbose: false
      